### ISSUE TITLE
Question: JSX Support

### ISSUE THREAD

**Issue by jcperez-ch** [thysultan/dio.js#15]
I wonder if adding `jsx` syntax support (probably a babel/webpack/rollup plugin) would be interesting for those users who already like react-like libraries.

So I can write the Welcome component as

```jsx
class Welcome {
	render() {
		return <h1>Hello ${this.props.name}</h1>;
	}
}
```

Any plans or work in progress?

**Comment by thysultan** [comment]
Babel/Typescript JSX is supported. You can use a pragma`/* @jsx h */` or alias `React =  dio`

**Comment by jcperez-ch** [comment]
Not very familiarized with the use of pragmas, but probably an example would make the community happier.

**Comment by thysultan** [comment]
By default Babel JSX transforms `<h1>Hello</h1>;` to `React.createElement("h1", null, "Hello")`

A pragma comment tells the JSX compiler to use the specified function as the calling function. In this case the suggested `/* @jsx h */` would output `h("h1", null, "Hello")`, you could also alias React to dio, or configure Babel to use `h` instead of `React.createElement` at a project level.

```js
{
  "plugins": [
    ["transform-react-jsx", { "pragma":"h" }]
  ]
}
```

I'll add this to the documentation.

**Comment by jcperez-ch** [comment]
Fantastic! Thank you so much

**Comment by thysultan** [comment]
Added to the docs – [Using JSX](https://dio.js.org/introduction.html#jsx)
