### ISSUE TITLE
errors shouldn't be logged if capurted

### ISSUE THREAD

**Issue by Zolmeister** [thysultan/dio.js#22]
if a component has `componentDidThrow` defined, it should not log to the console

https://github.com/thysultan/dio.js/blob/70dbe849b701d484373fd10d1733157fe661f53d/src/Boundary.js#L225

**Comment by thysultan** [comment]
I'm mostly reserving the need to log the error regardless so i can print a trace of the component tree that the error origins from, for example.

![Error Boundary](https://i.imgur.com/JFLGl6Z.png)

This is in the V8 branch, the parent > child tree could be many levels down, so it's useful to know how to get to the component which would be otherwise hard to do in user space.

**Comment by Zolmeister** [comment]
can this be achieved with `Error.captureStackTrace`?
or just mutate the error object before passing it in? (or both)

**Comment by thysultan** [comment]
I'm essentially mutating the error object [Error.js#L5-L28 (https://github.com/thysultan/dio.js/blob/V8/src/Core/Error.js#L5-L28). But that would only give you the last call site in this case `Child.render` the rest however are internal call sites i.e `getChildElement`... Where as what i wanted to archive was the the `<Child><Main> ... from render` tree construction above the JS error stack.
