### ISSUE TITLE
V9.x does not preselect select boxes properly

### ISSUE THREAD

**Issue by js-works** [thysultan/dio.js#58]
DIO's 9er version does NOT preselect the first item of select boxes by default.
This was working fine in DIO's 8.x versions.

Demo:
https://jsfiddle.net/fdegkc7m/

**Comment by thysultan** [comment]
This is related to [https://github.com/facebook/react/issues/12200](https://github.com/facebook/react/issues/12200) in that the implementation was trying to mimic this expected behavior, though that seems to have leaked to non-multiple select elements.

Out of curiosity i wonder what the spec says about this particular interaction/difference between multiple vs non-multiple default selection.

**Comment by thysultan** [comment]
Patched in [9.0.2](https://github.com/thysultan/dio.js/releases/tag/9.0.2)

**Comment by js-works** [comment]
Great ... muchas gracias :-)
